Select video from local playlists to play in mpv

diff --git a/bin/dsearch b/bin/dsearch
--- a/bin/dsearch
+++ b/bin/dsearch
@@ -36,6 +36,14 @@ create_menu() {
     while read -r url name; do
         printf -- '%s %s\n' "$name" "$url"
     done < "$confdir"/vimb/history
+
+
+    # This is for mpv playlists
+    ( cd "$XDG_DATA_HOME/mpv" || err "$XDG_DATA_HOME/mpv/ not found."
+    for file in *; do
+        puts "!mpv $file"
+    done
+    )
 }
 
 get_selection() {
@@ -48,15 +56,12 @@ get_selection() {
 handle_results() { # args -> launch
     case "$1" in
         !yt*) exec ythandler "${1:4}" ;;
-        !playlist*) exec playlisthandler "${1:10}" ;;
+        !pl*) exec playlisthandler "${1:4}" ;;
         !radio*) exec gmusichandler "${1:7}" ;;
         !song*) exec gsonghandler "${1:6}" ;;
         !book*) exec gbookhandler "${1:6}" ;;
         !code*) exec codehandler "${1:6}" ;;
-        #DDG handles this for you, so
-        #!aw*) vimb-run "https://wiki.archlinux.org/?search=${1:4}" ;;
-        #!gh*) vimb-run "https://github.com/search?utf8=%E2%9C%93&q=${1:4}&ref=simplesearch" ;;
-        #!g*) vimb-run "https://www.google.com/search?q=${1:3}" ;;
+        !mpv*) exec mpvhandler "${1:5}" ;;
         *) vimb-run "$1" ;;
     esac
 }
